# https://www.appveyor.com/docs/appveyor-yml/

version: 1.0.1.{build}
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2017
platform:
  - Any CPU
configuration:
  - Release
build:
  parallel: true
  project: bmconv.sln
environment:
  EnableNuGetPackageRestore: true
before_build:
  - nuget restore
after_build:
  - 7z a bmconv.zip -r %APPVEYOR_BUILD_FOLDER%/bmconv/bin/%CONFIGURATION%/*.dll
  - 7z a bmconv.zip -r %APPVEYOR_BUILD_FOLDER%/bmconv/bin/%CONFIGURATION%/*.exe
  - 7z a bmconv.zip LICENSE.txt
  - 7z a bmconv.zip README.md
  - copy bmconv.zip bmconv-v%APPVEYOR_BUILD_VERSION%.zip
  - copy bmconv.zip bmconv-latest.zip
artifacts:
  - path: bmconv-v%APPVEYOR_BUILD_VERSION%.zip
    name: WithVersion
  - path: bmconv-latest.zip
    name: Static
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
deploy:
  - provider: GitHub
    description: 'bmconv'
    auth_token:
      secure: u+MFjjY665AT4PHJ2bFMINBLnnnwSj1jLnNeFZoWfeYbomTNSPOmdahffmZa+dRH
    artifact: WithVersion            # upload all NuGet packages to release assets
    draft: false
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only